config/routes.rb
Rails.application.routes.draw do
  get 'rooms/show'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => "homes#top"
  get "home/about" => "homes#about"

  resources :books, only: [:index, :show, :edit, :create, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships,only:[:create,:destroy]
     get "followings" => "relationships#followings",as: "followings"
      get "followers" => "relationships#followers",as: "followers"
  end
  
    resources :messages,only:[:create]
     resources :rooms, only:[:create, :show]
  
  resources :groups do
    get "join" => "groups#join"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users

  validates :name, presence: true
  validates :introduction, presence: true
  attachment :image, destroy: false
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower,class_name: "User"
  belongs_to :followed,class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :entries,dependent: :destroy
  has_many :messages,dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  def follow(user_id)
      relationships.create(followed_id: user_id)
  end
  
  def unfollow(user_id)
      relationships.find_by(followed_id: user_id).destroy
  end
  
  def following?(user)
      followings.include?(user)
  end
 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         
  has_many :messages,dependent: :destroy
  has_many :entries,dependent: :destroy
  
  has_many :reverse_of_relationships,class_name: "Relationship",foreign_key: "followed_id",dependent: :destroy
  has_many :followers,through: :reverse_of_relationships,source: :follower
  has_many :relationships,class_name: "Relationship",foreign_key: "follower_id",dependent: :destroy
  has_many :followings,through: :relationships,source: :followed
  
  has_many :books
  has_many :group_users
  has_many :groups, through: :group_users
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  attachment :profile_image, destroy: false
  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def show
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
    def create
        @room = Room.create
        Entry.create(room_id: @room.id, user_id: current_user.id)
        Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(room_id: @room.id))
        redirect_to "/rooms/#{@room.id}"
    end

    def show
        @room = Room.find(params[:id])
      if Entry.where(user_id: current_user.id, room_id: @room.id).present?
        @messages = @room.messages.all
        @message = Message.new
        @entries = @room.entries
      else
        redirect_back(fallback_location: root_path)
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    @currentUserEntry = Entry.where(user_id: current_user.id)
    @userEntry = Entry.where(user_id: @user.id)
    if @user.id == current_user.id
      @msg = "ほかの方ともメッセージしよう"
    else
        @currentUserEntry.each do |cu|
          @userEntry.each do |u|
            if cu.room_id == u.room_id then
               @isRoom = true
               @roomId = cu.room_id
            end
          end
        end
        if isRoom != true
           @room = Room.new
           @entry = Entry.new
        end
    end
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>    @book.user_id = current_user.id

      <tr id="book_<%= book.id %>">
        <td><%= link_to user_path(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <td class="favorite-btn"><%= render "favorites/favorite-btn", book: book %></td>
        <td class="comments-count">コメント数: <%= book.book_comments.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
    	<%= render 'layouts/errors', obj: @book %>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', book_path(@book), class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <%= render 'layouts/errors', obj: @book %>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'index', books: @books%>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @book.user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: Book.new %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr id="book_<%= @book.id %>">
  		    <td><%= link_to user_path(@book.user) do %>
            <%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-icon.jpg") %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, book_path(@book) %></td>
          <td><%= @book.body %></td>
          <td class="favorite-btn"><%= render "favorites/favorite-btn", book: @book %></td>
          <td class="comments-count">コメント数: <%= @book.book_comments.count %></td>
          <% if @book.user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
            <td><%= link_to 'Destroy', book_path(@book), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
          <% end %>
        </tr>
      </table>
      <table class="book_comments">
        <%= render 'book_comments/index', book: @book %>
      </table>
      <%= form_with model:[@book,@book_comment] do |f| %>
        <%= f.text_area :comment, size:"90x5" %>
        <%= f.submit '送信'%>
      <% end %>
    </div>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="user-in">
<% @entries.each do |e| %>
    <h3><strong><a href="/users/<%= e.user.id %>"><%= e.user.email%></a></strong></h3>
<% end %>
<p>2人のDM❤️</p>
</div>

<div class="dmMain">
    <% @messages.each do |m| %>
        <strong><%= m.body %></strong>
        <small><%= m.user.email %>さん</small><hr>
    <% end %>

    <%= form_for @message do |f| %>
    <%= f.text_field :body, :placeholder => "メッセージを入力して下さい" , :size => 100 %>
    <%= f.hidden_field :room_id, :value => @room.id %>
    <br>
    <%= f.submit "送信する" %>
    <% end %>
</div>

<%= link_to "ユーザー一覧に戻る", users_path %>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>フォロー数</th>
    <th><%= link_to user.followings.count,user_followings_path(user.id) %></th>
  </tr>
  <tr>
    <th>フォロワー数</th>
    <th><%= link_to user.followers.count,user_followers_path(user.id) %></th>
    </tr>
  <tr>
    <% if current_user.following?(user) %>
    <th><%= link_to "Unfollow", user_relationships_path(user.id), method: :delete %></th>
    <% else %>
    <th><%= link_to "Follow", user_relationships_path(user.id), method: :post %></th>
    <% end %>
  </tr>
</table>

<div class='row'>
  <%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= link_to "グループを作成する", new_group_path %> | 
      <%= link_to "グループ一覧", groups_path %>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    　</div>
    　<div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>